name: CI

on:
  push:
    branches: [ "main" ]       # 必要に応じて変更
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-issue:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'   # ローカルと合わせる

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Run pytest
        id: tests
        continue-on-error: true     # 失敗しても後続ステップへ
        run: pytest -q

      - name: Auto-create Issue on failure
        if: steps.tests.outcome == 'failure'
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GH_TOKEN:          ${{ secrets.GH_TOKEN }}
        run: python scripts/auto_issue.py